README.md, app/demo/learnrtsp/learnrtsp.go, pkg/hls/fragment.go, pkg/hls/muxer.go, pkg/httpflv/client_pull_session.go, pkg/httpflv/server.go, pkg/httpflv/server_sub_session.go, pkg/innertest/innertest.go, pkg/logic/gop_cache.go, pkg/logic/group.go, pkg/logic/server_manager.go, pkg/rtmp/chunk_composer.go, pkg/rtmp/client_session.go, pkg/rtmp/server.go, pkg/rtmp/server_session.go, pkg/rtsp/packer.go, pkg/rtsp/rtcp.go, pkg/rtsp/rtcp_server.go, pkg/rtsp/rtp.go, pkg/rtsp/rtp_server.go, pkg/rtsp/rtsp.go, pkg/rtsp/server.go, pkg/rtsp/udp_server.go, test.sh
func (f *FragmentOP) WriteFrame 函数中不需要在循环内每次packet := make([]byte, 188)，在循环外或者直接使用成员变量就不用每次去分配内存了，已修改为FragmentOP成员变量。
=> 在最新代码上修改HLS模块的WriteFrame函数

pkg/hls/muxer.go
Put #EXT-X-ENDLIST to playlist after hls.Muxer.Dispose
=> HLS: close playlist after Muxer.Dispose

pkg/rtsp/pack.go, pkg/rtsp/server.go, pkg/rtsp/server_pub_session.go, pkg/rtsp/server_sub_session.go
=> support rtsp over tcp to push stream

pkg/base/websocket.go, pkg/httpflv/server_sub_session.go, pkg/httpts/server_sub_session.go
=> 支持ws-flv，ws-ts

Makefile, build/Dockerfile, build_linux.sh
=> build docker image

pkg/base/rtmp_t.go, pkg/rtmp/client_session.go, pkg/rtmp/message_packer.go, pkg/rtmp/server_session.go
=> [fix] rtmp 解决未处理PingRequest 回应

pkg/logic/group__core_streaming.go
=> Fix hls.enable: false causes runtime error

pkg/logic/server_manager.go
Bug fix - Allow standalone Mpegts recording without enabling record flv
=> Bug fix - Allow standalone Mpegts recording

app/lalserver/main.go
=> 添加-p参数设置运行时的路径

pkg/aac/aac.go
=> Supplementary AAC

pkg/rtsp/auth.go, pkg/rtsp/pack.go, pkg/rtsp/server_command_session.go
=> rtsp server support digest auth

conf/lalserver.conf.json
=> add rtsp auth config

pkg/rtmp/message_packer.go
=> solve push youtube failed

pkg/sdp/parse_logic.go
=> [bugfix]修复relay rtsp 2 rmp 无音频问题

pkg/avc/avc.go, pkg/hevc/hevc.go, pkg/remux/avpacket2rtmp.go, pkg/remux/var.go
=> [opt] 添加自定义流 SPS 合并到数据帧开关

pkg/base/t_http_an__notify.go
=> 增加回调ReadBytesSum和WroteBytesSum

app/demo/calcrtmpdelay/calcrtmpdelay.go, pkg/base/basic_session_stat.go, pkg/base/t_http_an__.go, pkg/base/t_session.go, pkg/rtsp/server_command_session.go
rename bitrate to bitrate_kbits
=> rename bitrate to bitrate_kbits

pkg/logic/config.go, pkg/logic/logic.go, pkg/logic/server_manager__.go
Add config raw content option so that we can read config from anywhere, local, remote, etc.
=> [feat] support: specify config raw content

app/demo/pullhttpflv/pullhttpflv.go
pullhttpflv demo支持拉取http-flv保存为flv文件
=> pullhttpflv demo support save flv file

conf/lalserver.conf.json, conf/lalserver.conf.json.tmpl, pkg/logic/config.go, pkg/logic/group__.go, pkg/remux/gop_cache.go, pkg/remux/gop_cache_mpegts.go, pkg/remux/gop_cache_test.go
=> [fix]gop增加单个gop包数量的限制

pkg/rtmp/chunk_divider.go
This code change helped me a lot when streaming over 30 streams.
Previously the machine's memory usage went to more than 3 GB.
But after this change, it is limited to 300 MB even when streaming 35 streams.
=> reduce memory consumption

pkg/base/avpacket.go, pkg/rtprtcp/rtp_unpacker.go, pkg/rtprtcp/rtp_unpacker_raw.go, pkg/rtsp/avpacket_queue.go, pkg/sdp/parse_logic.go, pkg/sdp/parse_raw.go, pkg/sdp/sdp.go
=> rtsp support G711(G711A/G711U)

pkg/base/t_http_an__.go, pkg/base/t_rtmp.go, pkg/logic/group__core_streaming.go, pkg/remux/remux.go, pkg/remux/rtmp2rtsp.go, pkg/sdp/pack.go, pkg/sdp/pack_test.go
=> rtmp2rtsp support g711a

pkg/rtsp/client_command_session.go
=> rtsp客户端在SETUP阶段收到461时切换transport

pkg/base/t_rtmp.go, pkg/hevc/hevc.go, pkg/logic/group__core_streaming.go, pkg/remux/rtmp2mpegts.go, pkg/remux/rtmp2rtsp.go
=> rtmp推流支持enhanced RTMP

pkg/base/avpacket.go
=> IsAudio interface add opus
